### ISSUE TITLE
Problems uploading to Azure App Service

### ISSUE THREAD

**Issue by DanielHofer001** [htl-perg-2019-20-5ahif/contact-list-exercise-DanielHofer001#1]
https://adressbook20190929051256.azurewebsites.net/contacts

:-) with this link it is now working

**Comment by rstropek** [comment]
Nice. You did not use *data annotations* (e.g. `[Required]`) in your code. However, because you sent me a link to your solution running in the cloud, the extra point is yours.

Greetings,
Rainer Stropek.
